test

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -1,20 +1,45 @@
-name: test
+name: pull request
 
 on:
+  push:
+    branches:
+      - develop
+      - master
   pull_request:
-    branches: [main]
+    branches:
+      - "**"
 
 jobs:
   build:
     runs-on: ubuntu-latest
 
     steps:
-      - name: action-slack
-        uses: 8398a7/action-slack@v3
+      # 해당 저장소의 코드를 가져옵니다.
+      - name: Checkout
+        uses: actions/checkout@v2
+
+      # Node 16 버전을 사용합니다.
+      - name: Install node
+        uses: actions/setup-node@v2
         with:
-          status: ${{ job.status }}
-          author_name: ${{ github.event.pull_request.html_url }} # default: 8398a7@action-slack
-          fields: pullRequest,commit,author,ref
-        env:
-          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # required
-        if: success() # Pick up events even if the job fails or is canceled.
+          node-version: "16"
+          cache: "npm"
+
+      # 설치된 yarn을 통해 패키지를 설치합니다.
+      - name: Install dependencies
+        run: npm install
+
+      # 테스트 수행과 그 테스트 결과를 xml파일로 생성합니다.
+      - name: Run tests
+        run: yarn test:report
+
+      # 테스트 결과를 담은 xml 파일을 레포트로 변환합니다.
+      - name: Test Report
+        uses: dorny/test-reporter@v1
+        if: success() || failure() # run this step even if previous step failed
+        with:
+          name: test-results
+          path: junit.xml
+          fail-on-error: "false"
+          reporter: jest-junit # Format of test results
+          token: ${{ secrets.GITHUB_TOKEN }}
